// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/AndiGanesha/authentication/repository (interfaces: IAuthenticationRepository)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	model "github.com/AndiGanesha/authentication/model"
	gomock "github.com/golang/mock/gomock"
)

// MockIAuthenticationRepository is a mock of IAuthenticationRepository interface.
type MockIAuthenticationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIAuthenticationRepositoryMockRecorder
}

// MockIAuthenticationRepositoryMockRecorder is the mock recorder for MockIAuthenticationRepository.
type MockIAuthenticationRepositoryMockRecorder struct {
	mock *MockIAuthenticationRepository
}

// NewMockIAuthenticationRepository creates a new mock instance.
func NewMockIAuthenticationRepository(ctrl *gomock.Controller) *MockIAuthenticationRepository {
	mock := &MockIAuthenticationRepository{ctrl: ctrl}
	mock.recorder = &MockIAuthenticationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAuthenticationRepository) EXPECT() *MockIAuthenticationRepositoryMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockIAuthenticationRepository) CreateUser(arg0 model.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockIAuthenticationRepositoryMockRecorder) CreateUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockIAuthenticationRepository)(nil).CreateUser), arg0)
}

// GetUser mocks base method.
func (m *MockIAuthenticationRepository) GetUser(arg0 string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", arg0)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockIAuthenticationRepositoryMockRecorder) GetUser(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockIAuthenticationRepository)(nil).GetUser), arg0)
}
